WebApp/Models/ErrorViewModel.cs
namespace WebApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApp/Models/Repository/ShirtsRepo.cs
using WebApp.Models;

namespace WebAapp.Models.Repository
{
    public static class ShirtsRepo
    {
        public static List<Shirt> Shirts = new List<Shirt>()
        {
            new Shirt() { ID = 1, Color = "Red", Size = 10, Gender = "man", Price = 2000 },
            new Shirt() { ID = 2, Color = "Blue", Size = 8, Gender = "man", Price = 3000},
            new Shirt() { ID = 3, Color = "Green", Size = 12, Gender = "man", Price = 4000}
        };

        public static bool ShirtExists(int id)
        {
            return Shirts.Any(s => s.ID == id);
        }

        public static Shirt? GetShirtByID(int id)
        {
            return Shirts.FirstOrDefault(s => s.ID == id);
        }

        public static bool SameShirtExists(string color, string size, string gender)
        {
            var result = from s in Shirts
                         where s.Color.Equals(color, StringComparison.OrdinalIgnoreCase)
                         && s.Size.ToString().Equals(size, StringComparison.OrdinalIgnoreCase)
                         && s.Gender.Equals(gender, StringComparison.OrdinalIgnoreCase)
                         select s;

            return result.Any();
        }

        public static void AddNewShirt(Shirt shirt)
        {
            int newID = Shirts.Max(s => s.ID);
            shirt.ID = newID + 1;

            Shirts.Add(shirt);
        }

        public static void UpdateShirt(Shirt shirt)
        {
            var existingShirt = GetShirtByID(shirt.ID);

            existingShirt.Color = shirt.Color;
            existingShirt.Size = shirt.Size;
            existingShirt.Gender = shirt.Gender;
            existingShirt.Price = shirt.Price;

        }

        public static void RemoveShirt(int id)
        {
            var shirt = GetShirtByID(id);
            Shirts.Remove(shirt);
        }
    }
}

WebApp/Models/Shirt.cs
using System.ComponentModel.DataAnnotations;
using WebAPI.Validations;


namespace WebApp.Models
{
    public class Shirt
    {
        public int ID { get; set; }

        [Required]
        public string? Color { get; set; }

        [Required]
        [ShirtSizeValidatorAtribute]
        public int Size { get; set; }

        [Required]
        public string? Gender { get; set; }

        [Required]
        public double Price { get; set; }
    }
}

WebApp/Models/Validations/ShirtSizeValidatorAtribute.cs
using System.ComponentModel.DataAnnotations;
using WebApp.Models;

namespace WebAPI.Validations
{
    public class ShirtSizeValidatorAtribute : ValidationAttribute
    {
        protected override ValidationResult? IsValid(object? value, ValidationContext validationContext)
        {
            var shirt = validationContext.ObjectInstance as Shirt;

            if (shirt != null && !string.IsNullOrWhiteSpace(shirt.Gender))
            {
                if (shirt.Gender.Equals("man", StringComparison.OrdinalIgnoreCase) && shirt.Size < 8)
                {
                    return new ValidationResult("Size is too small");
                }
                else if (shirt.Gender.Equals("women", StringComparison.OrdinalIgnoreCase) && shirt.Size < 4)
                {
                    return new ValidationResult("Size is too small");
                }
                else
                {
                    return ValidationResult.Success;
                }
            }
            else
            {
                return new ValidationResult("Invalid shirt data");
            }

        }
    }
}

WebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApp/Controllers/ShirtController.cs
using Microsoft.AspNetCore.Mvc;
using WebAapp.Models.Repository;
using WebApp.Data;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class ShirtController : Controller
    {
        private readonly IWebApiExecutor _apiExecutor;

        public ShirtController(IWebApiExecutor apiExecutor)
        {
            _apiExecutor = apiExecutor;
        }
        public async  Task<IActionResult> Index()
        {
            var shirts = await _apiExecutor.InvokeGet<List<Shirt>>("Home/getShirts");
            return View(shirts);
        }

        public IActionResult CreateShirt()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateShirt(Shirt shirt)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var rssponse = await _apiExecutor.InvokePost("Home/CreateShirts", shirt);

                    if (rssponse != null)
                    {
                        return RedirectToAction("Index");
                    }
                }
                catch (ApiException ex)
                {
                    HandleApiException(ex);
                }
            }
            return View(shirt);
        }

        public async Task<IActionResult> UpdateShirt(int shirtId)
        {
            try
            {
                var shirt = await _apiExecutor.InvokeGet<Shirt>($"Home/getShirtById/{shirtId}");
                if (shirt != null)
                {
                    return View(shirt);
                }
            }
            catch (ApiException ex)
            {
                HandleApiException(ex);
                return View();
            }

            return NotFound();

        }

        [HttpPost]
        public async Task<IActionResult> UpdateShirt(Shirt shirt)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _apiExecutor.InvokePut($"Home/UpdateShirt/{shirt.ID}", shirt);
                    return RedirectToAction("Index");
                }
                catch (ApiException ex)
                {
                    HandleApiException(ex);
                }

            }
            return View(shirt);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteShirt([FromForm]int shirtId)
        {
            try
            {
                var shirt = await _apiExecutor.InvokeDelete<Shirt>($"Home/RemoveShirt/{shirtId}");
                return RedirectToAction("Index");
            }
            catch (ApiException ex)
            {
                HandleApiException(ex);
                return View("Index", await _apiExecutor.InvokeGet<List<Shirt>>("Home/getShirts"));
            }
        }

        private void HandleApiException(ApiException ex)
        {
            if (ex.ErrorResponse != null
               && ex.ErrorResponse.Errors != null
               && ex.ErrorResponse.Errors.Count > 0)
            {
                foreach (var error in ex.ErrorResponse.Errors)
                {
                    ModelState.AddModelError(error.Key, string.Join(", ", error.Value));
                }
            }
            else if(ex.ErrorResponse != null)
            {
                ModelState.AddModelError("Error", ex.ErrorResponse.Title);
            }
            else
            {
                ModelState.AddModelError("Error", ex.Message);
            }
        }
    }
}

WebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Shirt" asp-action="Index">Shirts</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebApp/Views/Shirt/CreateShirt.cshtml
@model Shirt

<div class="container">

    <form asp-action="CreateShirt" method="post">
        <div class="text-danger" asp-validation-summary="All"></div>
        <div class="mb-2 row">
            <div class="col-2">
                <label asp-for="Color" class="col-form-label">Color</label>
            </div>
            <div class="col-8">
                <input asp-for="Color" type="text" class="form-control" required />
            </div>
            <div class="col">
                <span asp-validation-for="Color" class="text-danger"></span>
            </div>
        </div>

        <div class="mb-2 row">
            <div class="col-2">
                <label asp-for="Size" class="col-form-label">Size</label>
            </div>
            <div class="col-8">
                <input asp-for="Size" type="number" class="form-control" min="1" required />
            </div>
            <div class="col">
                <span asp-validation-for="Size" class="text-danger"></span>
            </div>
        </div>

        <div class="mb-2 row">
            <div class="col-2">
                <label asp-for="Price" class="col-form-label">Price</label>
            </div>
            <div class="col-8">
                <input asp-for="Price" type="number" class="form-control" min="1" required />
            </div>
            <div class="col">
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
        </div>

        <div class="mb-2 row">
            <div class="col-2">
                <label asp-for="Gender" class="col-form-label">Gender</label>
            </div>
            <div class="col-8">
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" asp-for="Gender" value="man" checked />
                    <label class="form-check-label" asp-for="Gender">Man</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" asp-for="Gender" value="women" />
                    <label class="form-check-label" asp-for="Gender">Women</label>
                </div>
            </div>
            <div class="col">
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
        </div>

        <div class="mb-2 row">
            <div class="col-2"></div>
            <div class="col-8 text-end">
                <input type="submit" class="btn btn-primary" value="Submit" />
            </div>
        </div>

    </form>
</div>

WebApp/Views/Shirt/Index.cshtml
@model List<Shirt>

<div class="container">
    <h3 class="text-center mb-3">Shirt's</h3>

    <div class="text-danger" asp-validation-summary="All"></div>

    @if(Model != null && Model.Count > 0)
    {
        <table class="table table-striped mb-3">
            <thead>
                <tr>
                    <th>Color</th>
                    <th>Size</th>
                    <th>Gender</th>
                    <th>Price</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>

            <tbody>
                @foreach (var shirt in Model)
                {
                    <tr>
                        <td>@shirt.Color</td>
                        <td>@shirt.Size</td>
                        <td>@shirt.Gender</td>
                        <td>@shirt.Price</td>

                        <td>
                            <a class="btn btn-secondary"
                               asp-controller="Shirt"
                               asp-action="UpdateShirt"
                               asp-route-shirtId="@shirt.ID">Edit</a>

                        </td>
                        <td>
                            <form asp-controller="Shirt" asp-action="DeleteShirt" method="post" onsubmit="return confirm('Sure to Delete');">
                                <input type="hidden" name="shirtId" value="@shirt.ID" />
                                <button type="submit" class="btn btn-danger">Delete</button>
                            </form>
                        </td>
                    </tr>
                }
            </tbody>

        </table>
    }
    else
    {
        <div class="alert alert-info text-center">
            No Shirts Available. Please add new shirts.
        </div>

    }

    <a class="btn btn-primary" asp-controller="Shirt" asp-action="CreateShirt">Create New</a>

</div>

WebApp/Views/Shirt/UpdateShirt.cshtml
@model Shirt

<div class="container">

    <form asp-action="UpdateShirt" method="post">
        <div class="text-danger" asp-validation-summary="All"></div>

        <input asp-for="ID" type="hidden" />
        <div class="mb-2 row">
            <div class="col-2">
                <label asp-for="Color" class="col-form-label">Color</label>
            </div>
            <div class="col-8">
                <input asp-for="Color" type="text" class="form-control" required />
            </div>
            <div class="col">
                <span asp-validation-for="Color" class="text-danger"></span>
            </div>
        </div>

        <div class="mb-2 row">
            <div class="col-2">
                <label asp-for="Size" class="col-form-label">Size</label>
            </div>
            <div class="col-8">
                <input asp-for="Size" type="number" class="form-control" min="1" required />
            </div>
            <div class="col">
                <span asp-validation-for="Size" class="text-danger"></span>
            </div>
        </div>

        <div class="mb-2 row">
            <div class="col-2">
                <label asp-for="Price" class="col-form-label">Price</label>
            </div>
            <div class="col-8">
                <input asp-for="Price" type="number" class="form-control" min="1" required />
            </div>
            <div class="col">
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
        </div>

        <div class="mb-2 row">
            <div class="col-2">
                <label asp-for="Gender" class="col-form-label">Gender</label>
            </div>
            <div class="col-8">
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" asp-for="Gender" value="man" checked />
                    <label class="form-check-label" asp-for="Gender">Man</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" asp-for="Gender" value="women" />
                    <label class="form-check-label" asp-for="Gender">Women</label>
                </div>
            </div>
            <div class="col">
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
        </div>

        <div class="mb-2 row">
            <div class="col-2"></div>
            <div class="col-8 text-end">
                <input type="submit" class="btn btn-primary" value="Save" />
                <a class="btn btn-secondary" asp-controller="Shirt" asp-action="Index">Back</a>

            </div>
        </div>

    </form>

</div>